/**
 * @file Automatically generated by barrelsby.
 */

export const CHECK_TOKEN_EXCEPTION = ['/swagger/', '/auth/login', '/auth/register'];

export const JWT_SECRET = 'test';

export const ERRORS = {
  USER_NOT_FOUND: 'User with such email is not found',
  INCORRECT_PASSWORD: 'Password is incorrect',
  USER_ALREADY_EXISTS: 'User with such email already exists',
  TOKEN_ERROR: 'Token is with error',
  FORBIDDEN: 'Forbidden',
  TOKEN_EXPIRED: 'Token expired',
  NOT_PROVIDED_TOKEN: 'Token expected',
};
