version: "3"
services:
  betslip_be:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "4013:4013"
    container_name: betslip_be
    environment:
      - CONFIG_DIR=docker
    networks:
      - coretech
networks:
  coretech:
